### ISSUE TITLE
How to work on the local machine

### ISSUE THREAD

**Issue by sky-admin** [elct9620/replicate-pastel-mix#1]
which file need edit?

**Comment by elct9620** [comment]
You need [cog](https://github.com/replicate/cog) and docker to run it in the local machine. And Nvidia GPU is required.

**Comment by sky-admin** [comment]
dont i need modify the config.ini file?

**Comment by sky-admin** [comment]
for example, i use blueboys-2d-v10 model, and convert the model dump into folder,
and i modify config.ini :
```ini
[generation]
model_id = ./blueboys-2d-v10
```

then i just run 
`cog predict -i prompt="1boy, blue" -i width=512  -i height=512`

now im waiting for result

**Comment by elct9620** [comment]
You need to run the `scripts/download.py` to get the model before use cog to run it.

**Comment by sky-admin** [comment]
ok i did it, thanks!!
